# src/main/resources/application.conf

app {
  http {
    host = "0.0.0.0"
    host = ${?APP_HOST} # Sobreposto pela env var APP_HOST, se existir
    
    port = 8080
    port = ${?APP_PORT}
  }

  graphql {
    path = "/graphql"
  }

  websocket {
    audit {
      path = "/audit/stream"
    }
  }
}

db {
  url = "jdbc:postgresql://localhost:5432/elections"
  url = ${?DB_URL}

  user = "elections"
  user = ${?DB_USER}

  password = "elections"
  password = ${?DB_PASSWORD}
}

security {
  jwt {
    secret = "change-me-in-production"
    secret = ${?JWT_SECRET}
    expiration-seconds = 86400
    expiration-seconds = ${?JWT_EXPIRATION_SECONDS}
  }
}